name: 'portfolio_tracking'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  portfolio_tracking:
    +materialized: view

    staging:
      +materialized: view
      +schema: STAGING

    refined:
      +materialized: view
      +schema: REFINED

    marts:
      +materialized: table
      +schema: MARTS

    portfolio:
      +materialized: table
      +schema: MART_PORTFOLIO

snapshots:
  portfolio_tracking:
    +target_schema: SNAPSHOTS